// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBakRWOQdzTEnhvRz_G32eCIh_EpORSw',
    appId: '1:799505581670:android:a8a14bdbf3df86271d8fa7',
    messagingSenderId: '799505581670',
    projectId: 'trademanager-44dba',
    storageBucket: 'trademanager-44dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxI1UqPT6muIEGuH08V0lvaT91YK7YgM',
    appId: '1:799505581670:ios:857408717dc638d51d8fa7',
    messagingSenderId: '799505581670',
    projectId: 'trademanager-44dba',
    storageBucket: 'trademanager-44dba.firebasestorage.app',
    iosBundleId: 'com.example.tradeDesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcxI1UqPT6muIEGuH08V0lvaT91YK7YgM',
    appId: '1:799505581670:ios:857408717dc638d51d8fa7',
    messagingSenderId: '799505581670',
    projectId: 'trademanager-44dba',
    storageBucket: 'trademanager-44dba.firebasestorage.app',
    iosBundleId: 'com.example.tradeDesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT7v2-VpP8M6mzc-KNYoqjxhz9SjILeqo',
    appId: '1:799505581670:web:35260fcd27b224d71d8fa7',
    messagingSenderId: '799505581670',
    projectId: 'trademanager-44dba',
    authDomain: 'trademanager-44dba.firebaseapp.com',
    storageBucket: 'trademanager-44dba.firebasestorage.app',
    measurementId: 'G-XXP7G6FGEK',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT7v2-VpP8M6mzc-KNYoqjxhz9SjILeqo',
    appId: '1:799505581670:web:35260fcd27b224d71d8fa7',
    messagingSenderId: '799505581670',
    projectId: 'trademanager-44dba',
    authDomain: 'trademanager-44dba.firebaseapp.com',
    storageBucket: 'trademanager-44dba.firebasestorage.app',
    measurementId: 'G-XXP7G6FGEK',
  );

}